spences10/twitter-bot-bootstrap

README.md

Update steps were in the wrong order :upside_down_face:

updae readme instructions

---

README.md

Pretty picture detailing where the `resources` are on the Heroku dashboard :smile:

Heroku picture :eyes:

---

src/bot.js

https://github.com/feross/standard

:memo: apply standard

---

package.json

chore(package): update snyk to version 1.31.0

---

package.json

fix(package): update snyk to version 1.34.1

---

package.json

fix(package): update snyk to version 1.34.3

---

package.json

fix(package): update twit to version 2.2.9

---

package.json

fix(package): update snyk to version 1.42.1

---

package.json

fix(package): update snyk to version 1.42.2

---

package.json

fix(package): update snyk to version 1.42.3

---

.package.json
package-lock.json
package.json
src/api/reply.js
src/api/retweet.js
src/bot.js

add console.lol

---

package.json

fix(package): update snyk to version 1.44.1

---

src/bot.js

added port listener for bot

---

package.json

fix(package): update snyk to version 1.48.1

---

package.json

fix(package): update snyk to version 1.49.1

---

package.json

fix(package): update snyk to version 1.54.1

---

package.json

fix(package): update snyk to version 1.59.0

---

package.json

fix(package): update snyk to version 1.61.0

---

package.json

fix(package): update snyk to version 1.62.2

---

package.json

fix(package): update snyk to version 1.65.1

---

package.json

fix(package): update snyk to version 1.73.0
